
version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: [node_modules]
      - run: yarn build
      - persist_to_workspace:
          root: /app
          paths: .

  release:
    working_directory: /app
    docker:
      - image: node:8
    steps:
      - attach_workspace:
          at: /app
      - run:
          name: Authenticate to NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/.npmrc
      - run:
          name: Bump version
          command: npm version --no-git-tag-version $CIRCLE_TAG
      - run:
          name: Publish package
          command: npm publish --access=public

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          filters:
            tags: {only: /.*/}
      - release:
          filters:
            tags: {only: /.*/}
            branches: {ignore: /.*/}
          requires: [build]
          context: org-global