/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SourceConfig = AcquiaSourceConfig | CircleCiSourceConfig | NewRelicSourceConfig;

export interface Configuration {
  /**
   * Elasticsearch connection details
   */
  elasticsearch: {
    [k: string]: any;
  };
  /**
   * Source plugins
   */
  sources: SourceConfig[];
}
/**
 * Configuration for the Acquia source
 */
export interface AcquiaSourceConfig {
  type: "acquia";
  /**
   * The name of the Elasticsearch index to write to (defaults to `acquia`)
   */
  index?: string;
  /**
   * The public key associated with your Acquia account
   */
  public_key: string;
  /**
   * The public key associated with your Acquia account
   */
  private_key: string;
  /**
   * The UUID of the environment you want metrics from
   */
  environmentId: string;
}
/**
 * Configuration for the CircleCI source
 */
export interface CircleCiSourceConfig {
  type: "circleci";
  /**
   * The name of the index to write to (defaults to `circleci`)
   */
  index?: string;
  /**
   * The API key associated with your CircleCI account
   */
  apiKey: string;
  /**
   * The VCS type of the source repository (eg: github)
   */
  vcsType: string;
  /**
   * The owner or organization that owns the repository
   */
  owner: string;
  /**
   * The repo slug
   */
  repo: string;
}
/**
 * Configuration for the New Relic source
 */
export interface NewRelicSourceConfig {
  type: "newrelic";
  /**
   * The name of the Elasticsearch index to write to (defaults to `newrelic`)
   */
  index?: string;
  /**
   * The API key associated with your New Relic account
   */
  apiKey: string;
  /**
   * The numeric app ID associated with the environment you want data from
   */
  appId: number;
  /**
   * Metric names from New Relic API
   */
  names?: any[];
}
