/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SourceConfig = AcquiaSourceConfig | CircleCiSourceConfig | NewRelicSourceConfig;

export interface Configuration {
  elasticsearch: ElasticSearchConnection;
  sources: SourceConfig[];
}
/**
 * The Elasticsearch connection information
 */
export interface ElasticSearchConnection {
  [k: string]: any;
}
export interface AcquiaSourceConfig {
  type: "acquia";
  /**
   * The public key associated with your Acquia account
   */
  public_key: string;
  /**
   * The public key associated with your Acquia account
   */
  private_key: string;
  /**
   * The UUID of the environment you want metrics from
   */
  environmentId: string;
}
export interface CircleCiSourceConfig {
  type: "circleci";
  /**
   * The API key associated with your CircleCI account
   */
  apiKey: string;
  /**
   * The VCS type of the source repository (eg: github)
   */
  vcsType: string;
  /**
   * The owner or organization that owns the repository
   */
  owner: string;
  /**
   * The repo slug
   */
  repo: string;
}
export interface NewRelicSourceConfig {
  type: "newrelic";
  /**
   * The API key associated with your New Relic account
   */
  apiKey: string;
  /**
   * The numeric app ID associated with the environment you want data from
   */
  appId: number;
}
